packages:
  - 'apps/*'
  - 'packages/*'

onlyBuiltDependencies:
  - '@prisma/client'
  - 'prisma'
  - '@nestjs/core'
  - 'esbuild'
  - 'unrs-resolver'

dangerouslyAllowAllBuilds: true

minimumReleaseAgeExclude:
  - supertest@7.3.0
