packages:
  - 'apps/*'
  - 'packages/*'
allowBuilds:
  '@nestjs/core': set this to true or false
  '@prisma/client': set this to true or false
  '@prisma/engines': set this to true or false
  prisma: set this to true or false
  unrs-resolver: set this to true or false
approve-builds:
  - '@nestjs/core'
  - '@prisma/client'
  - prisma
  - '@prisma/engines'
